### ISSUE TITLE
Currency ratios are incorrect,

### ISSUE THREAD

**Issue by August-ai** [EECS-2311-team-2/PennyPlanner#59]
Bug/Problem Report Form

Problem Report Number: 4
Reported By: MHD-Oubai Al-khimi
Date Reported: March 24, 2024
Program Name: Currency converter in Currency,java
Release Number: N/A
Version (Build) Identifier: N/A
Report Type: Coding error
Can Reproduce: Yes
Severity: Medium
Priority: Medium
Problem Summary: The currency ratios are incorrect, rendering the conversion faulty

Problem Description:
Detailed Description: When using Euro or GBP as input or output currency, we are shown an incorrect conversion which cannot be explained by fluctuation in currency price. This is due to hard coded incorrect values causing the error.

Steps to Reproduce: To reproduce the error, go to the Currency Converter page, then choose Eur or GBP as the input or output currency, proceed to write an amount and convert it, this will show an incorrect conversion.

Exact bug:

Resolution
Status: Open
Resolution: Pending
Resolved By: N/A
Resolution Date: N/A

**Comment by nabeelaia** [comment]
Currency Conversion Page:
Problem Summary: The conversion rates are wrong/not accurate due to the hard coded values. 
Refactoring: In the ConvertCurrency.java file, I created a method named ‘fetchcurrencyrates()’ in which real time conversion rates are called via an external API. In the Curreny.java file, I removed all the hard-coded conversion rates and replaced it with the currency codes. This way the conversion rates are real time and up to date. 


1. Extract interface for conversion logic
Code Smell/Design Issue: Tight Coupling and Single Responsibility Principle Violation
Before: ConvertCurrency class handles many tasks including UI interaction, conversion logic, and fetching conversion rates. This makes the class overly complex making it hard for unit testing and scalability. 
Refactoring: The currency converting logic and the rate fetching mechanism can be extracted into a separate interface. 
After: the Convertcurrency class now interacts with the separate interface for conversion tasks, simplifying the class and making it easier to test. 

2. Code Smell: Repetitive Code and Scalability Concerns 
Before: The initialization and management of XYChart.Series for different currencies are handled explicitly in the initialize method, leading to repetitive code. 
Refactoring Applied: Implement a Factory Pattern to encapsulate the creation of XYChart.Series instances  that initializes and returns a new series based on the given currency. 
After: Adding or removing currencies and their associated series becomes easier and cleaner, with less repetitive code in the initialize method. This approach enhances the application's scalability and readability.

3. Code smell: Primitive obsession. 
Before: The initial Currency enum only provided a basic name and conversion rate to Indian Rupees, relying on primitive data types for handling currency attributes.
Refactoring Applied: Implement a method in which currency rates are fetched from an external API in order to not rely on primitive data.
After: After adding a method to fetch real time rates for conversion, the code is much more accurate and clean.
